theme: jekyll-theme-minimal
# great resource: https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml
title: "Wiesner Theresa" 

tagline: Wiesner Theresa
email: theresa.wiesner@gmail.com
twitter_username: terrymosoly
twitter:
  - username: terrymosoly
description: “You cannot get through a single day without having an impact on the world around you. What you do makes a difference, and you have to decide what kind of difference you want to make.”- Jane Goodall Please recycle! 
author: WiesnerTheresa


logo: img/WIESNER_INP au travail.jpg
favicon: img/WIESNER_INP au travail.jpg
# background-image: img/IMG_3594.JPG

# # Reading Files
# include:
#   - _pages

# # Collections
# collections:
#   playground:
#     output: true
#     permalink: /:collection/:path/
# #   collection2:
# #     output: true
# #     permalink: /:collection/:path/

# # Defaults
# defaults:
#   -
#     scope:
#       path: ""
#       type: "pages"
#     values:
#       layout: page
#       hero_image: img/thumbnail_Theresa_Wiesner_crop.png

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# remote_theme: chrisrhymes/bulma-clean-theme
